### ISSUE TITLE
AttributeError: module 'asyncio.coroutines' has no attribute '_is_coroutine'

### ISSUE THREAD

**Issue by VIJAYVIVU** [nitingarg691/Chat-Application#1]
![Screenshot from 2020-09-12 10-26-19](https://user-images.githubusercontent.com/56530369/92987685-73c07380-f4e2-11ea-9b3a-629f80989f48.png)
Checkout video looks fine. Please check this and help to fix it out .
Thanks in advance

**Comment by nitingarg691** [comment]
I have added the Redis-server folder. so you have to run redis-server.exe before running the project and also check the project requirements.

**Comment by VIJAYVIVU** [comment]
Thanks. I used a Linux server .exe is not supported any other suggestion.
will go with the install of Redis on my system ubuntu will work are need to alternate code.

**Comment by VIJAYVIVU** [comment]
![image](https://user-images.githubusercontent.com/56530369/92995271-b7859e00-f51f-11ea-9a0c-ada7b76366e0.png)
cant able to send and receive messages. please help to fix it out got those error at Linux. Thanks in advance

**Comment by nitingarg691** [comment]
You have to run redis-server after that websocket will connect
